config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stokes_distributing.stokes.urls', namespace='stokes'))
]

stokes_distributing/stokes/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from . import views

app_name = 'stokes'
urlpatterns = [
    path('', views.index, name='index'),
    path('beers', views.beers, name='beers'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('events', views.events, name='events'),
    path('jobs', views.jobs, name='jobs')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Stokes Distributing Admin'
admin.site.site_title = 'Stokes Admin'
admin.site.index_title = 'Stokes Admin'

stokes_distributing/stokes/models.py
import base64
from django.db import models


class Application(models.Model):
    name = models.CharField(max_length=50, blank=True)
    job_title = models.CharField(max_length=20, blank=True)
    phone_number = models.CharField(max_length=20, blank=True)
    email = models.CharField(max_length=50, blank=True)
    submitted = models.DateTimeField(auto_now_add=True, blank=True)
    viewed = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class ApplicationFile(models.Model):
    application = models.OneToOneField(Application, on_delete=models.CASCADE, primary_key=True)
    binary_data = models.BinaryField(blank=True, null=True, editable=True)
    content_type = models.CharField(max_length=100)
    filename = models.CharField(max_length=150, blank=True)


class Brand(models.Model):
    name = models.CharField(max_length=50)
    brands_website = models.CharField(max_length=100, default="")
    image = models.BinaryField(blank=True, null=True, editable=True)
    content_type = models.CharField(max_length=100)
    filename = models.CharField(max_length=150, blank=True)

    def image_as_base64(self):
        if self.image:
            base64_data = base64.b64encode(self.image).decode('utf-8')
            return f'data:{self.content_type};base64,{base64_data}'
        return None

    def __str__(self):
        return self.name


class Event(models.Model):
    title = models.CharField(max_length=60)
    start_time = models.CharField(max_length=15)
    end_time = models.CharField(max_length=15)
    date = models.CharField(max_length=50)
    location = models.CharField(max_length=70, blank=True)
    link_url = models.CharField(max_length=500, blank=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.title


class EventImage(models.Model):
    event = models.OneToOneField(Event, on_delete=models.CASCADE, primary_key=True)
    binary_data = models.BinaryField(blank=True, null=True, editable=True)
    content_type = models.CharField(max_length=100)
    filename = models.CharField(max_length=150, blank=True)

    def binary_data_as_base64(self):
        if self.binary_data:
            base64_data = base64.b64encode(self.binary_data).decode('utf-8')
            return f'data:{self.content_type};base64,{base64_data}'
        return None


class Message(models.Model):
    name = models.CharField(max_length=50, blank=True)
    phone_number = models.CharField(max_length=20, blank=True)
    email = models.CharField(max_length=50, blank=True)
    subject = models.CharField(max_length=50, blank=True)
    message = models.TextField()

    def __str__(self):
        return self.name


class NewProduct(models.Model):
    title = models.CharField(max_length=50, blank=True)
    image = models.BinaryField(blank=True, null=True, editable=True)
    content_type = models.CharField(max_length=100)
    filename = models.CharField(max_length=150, blank=True)

    def image_as_base64(self):
        if self.image:
            base64_data = base64.b64encode(self.image).decode('utf-8')
            return f'data:{self.content_type};base64,{base64_data}'
        return None

    def __str__(self):
        return self.title

stokes_distributing/stokes/forms.py
from django import forms
from django.core.files.uploadedfile import InMemoryUploadedFile
from .models import Brand, EventImage, NewProduct


class NoInput(forms.Widget):
    input_type = "hidden"
    template_name = ""

    def render(self, name, value, attrs=None, renderer=None):
        return ""


class BrandForm(forms.ModelForm):
    image = forms.ImageField(required=False)
    filename = forms.CharField(required=False, widget=NoInput)
    content_type = forms.CharField(required=False, widget=NoInput)

    class Meta:
        model = Brand
        fields = ['name', 'brands_website', 'image', 'filename', 'content_type']

    def __init__(self, *args, **kwargs):
        super(BrandForm, self).__init__(*args, **kwargs)
        if self.instance and self.instance.image:
            base64_image = self.instance.image_as_base64()
            self.fields['image'].widget = forms.ClearableFileInput(attrs={
                'data-preview': base64_image}
            )
            self.fields['image'].help_text = (
                f'''<img src="{base64_image}" alt="Current image"
                    style="width: auto; height: 150px;" /><br>'''
            )

    def clean(self):
        cleaned_data = super().clean()
        uploaded_file = cleaned_data.get('image')

        if isinstance(uploaded_file, InMemoryUploadedFile):
            cleaned_data['image'] = uploaded_file.read()
            cleaned_data['content_type'] = uploaded_file.content_type
            cleaned_data['filename'] = uploaded_file.name
        elif self.instance.pk and not isinstance(uploaded_file, InMemoryUploadedFile):
            cleaned_data['image'] = self.instance.image
            cleaned_data['content_type'] = self.instance.content_type
            cleaned_data['filename'] = self.instance.filename

        return cleaned_data


class EventImageForm(forms.ModelForm):
    binary_data = forms.ImageField(required=False, label='Image')
    filename = forms.CharField(required=False, widget=NoInput)
    content_type = forms.CharField(required=False, widget=NoInput)

    class Meta:
        model = EventImage
        fields = ['binary_data', 'filename', 'content_type']

    def __init__(self, *args, **kwargs):
        super(EventImageForm, self).__init__(*args, **kwargs)
        if self.instance and self.instance.binary_data:
            base64_image = self.instance.binary_data_as_base64()
            self.fields['binary_data'].widget = forms.ClearableFileInput(attrs={
                'data-preview': base64_image}
            )
            self.fields['binary_data'].help_text = (
                f'''<img src="{base64_image}" alt="Current image"
                    style="width: auto; height: 150px;" /><br>'''
            )

    def clean(self):
        cleaned_data = super().clean()
        uploaded_file = cleaned_data.get('binary_data')

        if uploaded_file:
            cleaned_data['binary_data'] = uploaded_file.read()
            cleaned_data['content_type'] = uploaded_file.content_type
            cleaned_data['filename'] = uploaded_file.name

        return cleaned_data


class NewProductForm(forms.ModelForm):
    image = forms.ImageField(required=False)
    filename = forms.CharField(required=False, widget=NoInput)
    content_type = forms.CharField(required=False, widget=NoInput)

    class Meta:
        model = NewProduct
        fields = ['title', 'image', 'filename', 'content_type']

    def __init__(self, *args, **kwargs):
        super(NewProductForm, self).__init__(*args, **kwargs)
        if self.instance and self.instance.image:
            base64_image = self.instance.image_as_base64()
            self.fields['image'].widget = forms.ClearableFileInput(attrs={
                'data-preview': base64_image}
            )
            self.fields['image'].help_text = (
                f'''<img src="{base64_image}" alt="Current image"
                    style="width: auto; height: 150px;" /><br>'''
            )

    def clean(self):
        cleaned_data = super().clean()
        uploaded_file = cleaned_data.get('image')

        if isinstance(uploaded_file, InMemoryUploadedFile):
            cleaned_data['image'] = uploaded_file.read()
            cleaned_data['content_type'] = uploaded_file.content_type
            cleaned_data['filename'] = uploaded_file.name
        elif self.instance.pk and not isinstance(uploaded_file, InMemoryUploadedFile):
            cleaned_data['image'] = self.instance.image
            cleaned_data['content_type'] = self.instance.content_type
            cleaned_data['filename'] = self.instance.filename

        return cleaned_data

stokes_distributing/stokes/views.py
from django.shortcuts import render
from django.core.mail import EmailMessage
from django.conf import settings
from .models import Application, ApplicationFile, Brand, Event, Message, NewProduct


def index(request):
    new_products = NewProduct.objects.all()
    brands = Brand.objects.all()

    return render(request, "stokes/index.html", {
        "new_products": new_products,
        "brands": brands
    })


def beers(request):
    brands = Brand.objects.all()
    return render(request, "stokes/beers.html", {
        "brands": brands
    })


def about(request):
    return render(request, "stokes/about.html")


def contact(request):
    if (request.method == "POST"):
        Name = request.POST.get("name")
        Number = request.POST.get("number")
        Email = request.POST.get("email")
        Subject = request.POST.get("subject")
        Mesg = request.POST.get("message")

        Msg = Message()

        Msg.name = Name
        Msg.phone_number = Number
        Msg.email = Email
        Msg.subject = Subject
        Msg.message = Mesg

        Msg.save()

        return render(request, "stokes/contact.html", {
            "message": "Message sent!"
        })

    return render(request, "stokes/contact.html")


def jobs(request):
    if (request.method == "POST"):

        position = request.POST.get("position")
        name = request.POST.get("name")
        number = request.POST.get("number")
        email = request.POST.get("email")
        resume = request.FILES['resume'].read()
        content_type = request.FILES['resume'].content_type
        file_name = f'{name}-resume.pdf'

        if (Application.objects.filter(email=email, job_title=position).exists()):
            app = Application.objects.select_related('applicationfile').get(email=email,
                                                                            job_title=position)
            app.name = name
            app.phone_number = number
            app.save()
            if hasattr(app, 'applicationfile'):
                app.applicationfile.binary_data = resume
                app.applicationfile.content_type = content_type
                app.applicationfile.file_name = file_name
                app.applicationfile.save()
            else:
                ApplicationFile(application=app, binary_data=resume,
                                content_type=content_type, filename=file_name).save()
        else:
            application = Application()
            application.name = name
            application.job_title = position
            application.phone_number = number
            application.email = email
            application.save()
            ApplicationFile(application=application, binary_data=resume,
                            content_type=content_type, filename=file_name).save()

        subject = f'Application recieved from {name}'
        body = f"Name: {name}\nPosition:{position}\nPhone Number: {number}\nEmail: {email}"
        from_email = settings.EMAIL_HOST_USER
        to_email = settings.DEFAULT_TO_EMAIL
        # Create the email
        email = EmailMessage(subject, body, from_email, to_email)

        # Attach the binary data
        email.attach(file_name, resume, content_type)

        # Send the email
        email.send()

        return render(request, "stokes/jobs.html", {
            "message": "Application submitted!"
        })

    return render(request, "stokes/jobs.html")


def events(request):
    events = Event.objects.select_related('eventimage').all()
    return render(request, "stokes/events.html", {
        "events": events,
        "first_range": range(0, len(events) + 1, 3),
        "second_range": range(len(events))
    })


def product_finder(request):
    return render(request, "stokes/product_finder.html")

stokes_distributing/templates/stokes/about.html
{% load static %}
<!doctype html>
<html class="no-js" lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="x-ua-compatible" content="ie=edge">
		<title>Stokes Distributing - About</title>
		<meta name="description" content="Learn about our history and how we got to where are today here.">
		<meta name="keywords" content="Coors, Miller, Miller Lite, InBev, Imports, Craft Beer, Abita, Samuel Adams, Hattiesburg, McComb, Mississippi, South Mississippi">
		<meta name="author" content="Douglas Mumme">
		<link rel="canonical" href="https://www.stokesdistributing.com/about" />
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<!-- Favicons -->
		<link rel="apple-touch-icon" sizes="57x57" href="{% static 'stokes/apple-touch-57.png' %}" />
		<link rel="apple-touch-icon" sizes="114x114" href="{% static 'stokes/apple-touch-114.png' %}" />
		<link rel="apple-touch-icon" sizes="72x72" href="{% static 'stokes/apple-touch-72.png' %}" />
		<link rel="apple-touch-icon" sizes="144x144" href="{% static 'stokes/apple-touch-144.png' %}" />
		<link rel="icon" href="{% static 'stokes/favicon.ico' %}" />

		<!-- Fonts -->
		<link href="https://fonts.googleapis.com/css?family=Anonymous+Pro%7CAnton" rel="stylesheet">
		<link href='https://fonts.googleapis.com/css?family=Raleway:600,900,400' rel='stylesheet' type='text/css'>

		<!-- Vendor -->
		<link rel="stylesheet" type="text/css" href="{% static 'stokes/css/normalize.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'stokes/css/bootstrap.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'stokes/css/font-awesome.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'stokes/css/animate.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'stokes/css/introLoader.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'stokes/css/featherlight.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'stokes/css/slick.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'stokes/css/slick-theme.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'stokes/css/tooltipster.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'stokes/css/selectric.custom.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'stokes/css/main.css' %}">
		
		<!-- Page Specific Styles -->
		<link rel="stylesheet" type="text/css" href="{% static 'stokes/css/aos.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'stokes/css/remodal.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'stokes/css/remodal-default-theme.custom.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'stokes/css/popup.css' %}">
		<!-- Modernizr -->
		<script src="{% static 'stokes/js/vendor/modernizr.js' %}"></script>

		
		<meta property="og:site_name" content="Stokes Distributing">
 		<meta property="og:title" content="Stokes Distributing">
 		<meta property="og:type" content="website" />
 		<meta property="og:image" content="{% static 'stokes/favicon.ico' %}"/>
 		<meta property="og:url" content="www.stokesdistributing.com">
 		<meta property="og:description" content="Product portfolio and corporate information for Stokes Distributing, a beer and light wine distributor in Hattiesburg, Mississippi and McComb, Mississippi">
		

	</head>
	<body class="page">
		<!-- Button trigger modal -->
		<article class="box">
			<div class="box-left">
				<br>
				<br>
				<br>
				<br>
				<br>
				<br>
				<br>
			</div>
			<div class="box-right">
			  <h3>Age Verification</h3>
			  <p>By clicking enter, I certify that I am over the age of 21 and will comply with the above statement.</p>
			  
			  <a href="{% url 'stokes:about' %}" class="btn btn-alpha"  id="refresh-page">ENTER</a>
			  
			  <p class="decor-line"><span>Or</span></p>
			  
			  <a href="#" class="btn btn-beta" id="reset-session">EXIT</a>
			  
			  <small>Always enjoy responsibily.</small>
			</div>
			</div>
		</article>
		  
		<div class="overlay-verify"></div>
		<!--[if lt IE 8]>
			<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
		<![endif]-->

		<div class="header-wrap" style="background-image: url({% static 'stokes\img\107979597_3430974780269751_2656095547854316710_o.jpg' %});">

			<!-- Navigation -->
			<div class="container-fluid">
				<div class="topbar topbar-hero row">
					<div class="nav-wrapper col-md-12 hidden-sm hidden-xs">
						<nav class="list-unstyled main-navigation">
							<a href="{% url 'stokes:index' %}"><h2 style="display: inline; color: white; font-family: HelveticaNeue-Light;">Stokes Distributing</h2></a>
							<!-- Left Menu -->
							<ul class="list-unstyled list-inline topbar-right ">
								<li><a href="{% url 'stokes:index' %}">Home</a></li>
								<li><a href="{% url 'stokes:beers' %}">Beers</a></li>
								<li class="current"><a href="{% url 'stokes:about' %}">About</a></li>
								<li><a href="{% url 'stokes:jobs' %}">Jobs</a></li>
								<li><a href="{% url 'stokes:events' %}">Events</a></li>
								<li><a href="{% url 'stokes:contact' %}">Contact</a></li>
							</ul>
						</nav>
					</div>
				

					<!-- Mobile Navigation Toggle -->
					<div class="mobile-toggle topbar-right col-sm-6 col-xs-6 hidden-md hidden-lg">
						<a href="javascript:void(0);" class="toggle-panel"><i class="fa fa-bars"></i></a>
					</div>
				</div>
			</div>
			
			<!-- Page Header -->
			<header class="header page-header image-header">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<h1 class="page-title"><span>About</span></h1>
						</div>
					</div>
				</div>			
			</header>
		</div>

		<!-- Page Content -->
		<main class="entry-content">

			<!-- Breadcrumbs -->
			<div class="page-breadcrumbs">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<ol class="list-inline list-unstyled" itemscope itemtype="http://schema.org/BreadcrumbList">
								<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
									<a itemprop="item" href="{% url 'stokes:index' %}"><span itemprop="name">Home</span></a>
									<meta itemprop="position" content="1" />
								</li>
								<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
									<span itemprop="name">About</span>
									<meta itemprop="position" content="2" />
								</li>
							</ol>
						</div>
					</div>
				</div>
			</div>

			<div class="container">
				<br>
				<div>
					<div>
						<h2 style="color: rgb(168, 37, 37); ">Our Mission:</h2>
					</div>
					<div style="float: left;">
						<p style="font-size: large;">“Exceed the expectations of our customers through our team’s passion and dedication to providing quality products and outstanding service to the people of South MS. ”</p>
					</div>
				</div>
			</div>

			<section class="page-section">
				<div class="container">
					<div class="row">
						<div class="col-md-6">
							<h3 style="color: rgb(168, 37, 37); ">Our History</h3>
							<p>After World War II, a man named Dick Stokes began looking for something new in his life. In 1947, he decided to buy a distributing company based in Hattiesburg, MS and thus created Stokes Distributing Company, Inc. In the beginning, he started with three small trucks in a small warehouse in downtown Hattiesburg to cover Forrest and Perry counties, along with the city limits of Laurel to deliver its beer. It was his dedication to excellent customer service, providing quality life for his employees, and his generosity to the community that has shaped Stokes Distributing Company today.</p>
							<p>The Company now employs over 65 people, has 2 different locations, and delivers product from the Alabama Line to the Louisiana Line, covering 22 counties with over 15 route trucks.</p>
						</div>
						<div class="col-md-6">
							<div class="about-slider">
								<a class="about-single-gallery" href="{% static 'stokes\img\meeting-pic.jpg' %}"><img alt="" src="{% static 'stokes\img\meeting-pic.jpg' %}"></a>
								<a class="about-single-gallery" href="{% static 'stokes\img\crew-pic.jpg' %}"><img alt="" src="{% static 'stokes\img\crew-pic.jpg' %}"></a>
								<a class="about-single-gallery" href="{% static 'stokes\img\donation-pic.jpg' %}"><img alt="" src="{% static 'stokes\img\donation-pic.jpg' %}"></a>
								<a class="about-single-gallery" href="{% static 'stokes\img\donation-pic2.jpg' %}"><img alt="" src="{% static 'stokes\img\donation-pic2.jpg' %}"></a>
								<a class="about-single-gallery" href="{% static 'stokes\img\crew-pic3.jpg' %}"><img alt="" src="{% static 'stokes\img\crew-pic3.jpg' %}"></a>
							</div>
						</div>
					</div>
				</div>
			</section>
			
		</main><!-- /.enry-content -->

		<!-- Footer -->
		<div class="footer-wrapper">

			 <!-- Secondary Footer -->
			 <footer class="footer-secondary">
				<div class="container">
					<div class="row">
						<!-- Copyright -->
						<div class="footer-secondary-left col-lg-6 col-md-6 col-sm-6 col-xs-12">
							<p style="color: black; margin-top: 15px;">Stokes Distributing encourages adults to drink responsibily.</p>
						</div>
						<div class="footer-secondary-left col-lg-2 col-md-2 col-sm-2 col-xs-12">
							<a class="admin-link" href="{% url 'admin:index' %}"><p style="color: black; margin-top: 15px;">Admin</p></a>
						</div>
						<div class="footer-secondary-right col-lg-4 col-md-6 col-sm-6 col-xs-12">
							<p style="display: inline-block;"> Social Media:</p>
							<!-- Social Icons -->
							<ul class="social-icons list-unstyled list-inline" style="display: inline-block;">
								<li><a class="fa fa-facebook tooltipster" title="Facebook" href="https://www.facebook.com/stokesdistributing"></a></li>
								<li><a class="fa fa-twitter tooltipster" title="Twitter" href="https://twitter.com/StokesDist"></a></li>
								<li><a class="fa fa-instagram tooltipster" title="Instagram" href="https://www.instagram.com/stokesdist/"></a></li>
							</ul>
						</div>
					</div>
				</div>
			</footer>
		</div>
		
		<!-- Off-Page Content -->

		<!-- Mobile Navigation (Left Panel) -->
		<div id="panel-left">
			<div id="sidebar-wrapper" class="sidebar-wrapper">
				<nav class="mobile-navigation">
					<ul class="list-unstyled">
						<li><a href="{% url 'stokes:index' %}">Home</a></li>
						<li><a href="{% url 'stokes:beers' %}">Beers</a></li>
						<li><a href="{% url 'stokes:about' %}">About</a></li>
						<li><a href="{% url 'stokes:jobs' %}">Jobs</a></li>
						<li><a href="{% url 'stokes:events' %}">Events</a></li>
						<li><a href="{% url 'stokes:contact' %}">Contact</a></li>
					</ul>
				</nav>
				<a class="close-sidebar" href="javascript:void(0)"><i class="fa fa-times"></i></a>
			</div>
		</div>

		<!-- Preloader -->
		<div class="introLoading"></div>

		<!-- Back to Top -->
		<div>
			<a class="back-to-top fa fa-chevron-up" href="javacript:void(0);"></a>
		</div>

		<!-- Core -->
		<script src="{% static 'stokes/js/vendor/jquery.min.js' %}"></script>
		<script src="{% static 'stokes/js/vendor/jquery-ui.min.js' %}"></script>
	   
		<!-- Vendor -->
		<script src="{% static 'stokes/js/vendor/bootstrap.min.js' %}"></script>
		<script src="{% static 'stokes/js/vendor/jquery.selectric.min.js' %}"></script>
		<script src="{% static 'stokes/js/vendor/gmaps.min.js' %}"></script>
		<script src="{% static 'stokes/js/vendor/jquery.waypoints.min.js' %}"></script>
		<script src="{% static 'stokes/js/vendor/SmoothScroll.js' %}"></script>
		<script src="{% static 'stokes/js/vendor/jquery.hoverIntent.js' %}"></script>
		<script src="{% static 'stokes/js/vendor/jquery.simpler-sidebar.min.js' %}"></script>
		<script src="{% static 'stokes/js/vendor/jquery.introLoader.pack.min.js' %}"></script>
		<script src="{% static 'stokes/js/vendor/featherlight.min.js' %}"></script>
		<script src="{% static 'stokes/js/vendor/featherlight.gallery.min.js' %}"></script>
		<script src="{% static 'stokes/js/vendor/slick.min.js' %}"></script>
		<script src="{% static 'stokes/js/vendor/jquery.tooltipster.min.js' %}"></script>
		<script src="{% static 'stokes/js/vendor/imagesloaded.pkgd.min.js' %}"></script>
		<script src="{% static 'stokes/js/vendor/isotope.pkgd.min.js' %}"></script>
		<script src="{% static 'stokes/js/vendor/packery-mode.pkgd.min.js' %}"></script>
		<script src="{% static 'stokes/js/vendor/parsley.min.js' %}"></script>

		<!-- Vendor (Page Specific) -->
		<script src="{% static 'stokes/js/vendor/remodal.min.js' %}"></script>
	   
		<!-- Theme -->
		<script src="{% static 'stokes/js/main.js' %}"></script>
		<script src="{% static 'stokes/js/popup.js' %}"></script>

	</body>
</html>